### PR TITLE
Discord++ Integration 

### LINKED ISSUE #111: Integration of DPP (Discord ++ Library)
**Is your feature request related to a problem? Please describe.**
As the Discord, RPC Library is not supported, and the GameSDK isn't suitable or well supported either, I propose the plugin moves to Discord++ which supports the majority of the Discord API features - This means that more of the useful features that can't currently be done, can be added.  

**Describe the solution you'd like**
Integration of DPP (D++)

**Describe alternatives you've considered**
DiscordGameSDK - Which is potentially itself being deprecated based on the Discord API Server
`Over the next few months, we'll be evaluating the functionality of the GameSDK. Obviously some game-store related features will not be supported past March, like purchasing new SKUs, but the rest has not yet been decided. There are live games running from Discord that have integrated the GameSDK, and as long as those players are still playing those games on Discord, we don't want to remove their ability to do so
We'll also be migrated the issues in the gamesdk and dispatch issue tracker to the main issue tracker and tagging them appropriately, so that they have eyes on them. Having everything in separate places is just too much to keep track of right now`

**Additional context**
https://dpp.dev/index.html
https://github.com/brainboxdotcc/DPP

### PR DESCRIPTION
**Pull request by Edstub207**
Closes #111

### CODE REVIEW

**Comment by fredemmott** [comment]
FWIW, both that library - and IME the websocket API it uses to talk to discord - are *heavily* focussed on bots and app integrations.

When I tried using the websocket API instead of the named pipe API, actions would *only* affect my app, not the discord client state

For example, the mute state would only affect the ability of my app to send audio data, it wouldn't affect whether the user was muted in channels they'd joined in the client.

If this is still the case, this is unsuitable for this project.

**Comment by Edstub207** [comment]
> If this is still the case, this is unsuitable for this project.

Interesting! I'll have a play around and see if I can make any progress - It's a real shame if that's still the case with these integrations and Discord doesn't have any plans to maintain that.

**Comment by fredemmott** [comment]
> When I tried using the websocket API instead of the named pipe API, actions would only affect my app, not the overall discord client state


Strangely enough ,in my testing (around a year ago), this affected both the gateway API and the (also deprecated) local websocket API

**Comment by fredemmott** [comment]
I guess that makes sense for the 'in-game voice' feature though

**Comment by Edstub207** [comment]
Closing this off - Not worth the effort with Elgato having an official Discord plugin now > https://twitter.com/elgato/status/1485979660844339200

**Pull request closed without merging**
